# https://github.com/actions/labeler/blob/master/README.md

test:
  - any: ['test/**/*']
    all: ['!test/**/*.approved.txt']

github_actions:
  - .github/**/*

code style:
  - .editorconfig

docs:
  - README.md
  - doc/**/*

samples:
  - samples/**/*

applicationstatus:
  - src/Pulse.ApplicationStatus/**/*

arrangodb:
  - src/Pulse.ArangoDb/**/*

aws:
  - src/Pulse.Aws.*/**/*

azure:
  - src/Pulse.Azure*/**/*

consul:
  - src/Pulse.Consul/**/*

cosmosdb:
  - src/Pulse.CosmosDb/**/*

dapr:
  - src/Pulse.Dapr/**/*

documentdb:
  - src/Pulse.DocumentDb/**/*

dynamodb:
  - src/Pulse.DynamoDb/**/*

elasticsearch:
  - src/Pulse.Elasticsearch/**/*

eventstore:
  - src/Pulse.EventStore*/**/*

cloudfirestore:
  - src/Pulse.Gcp.CloudFirestore/**/*

gremlin:
  - src/Pulse.Gremlin/**/*

hangfire:
  - src/Pulse.Hangfire/**/*

ibmmq:
  src/Pulse.IbmMQ/**/*

influxdb:
  src/Pulse.InfluxDB/**/*

kafka:
  - src/Pulse.Kafka/**/*

kubernetes:
  - src/Pulse.Kubernetes/**/*

mongodb:
  - src/Pulse.MongoDb/**/*

mysql:
  - src/Pulse.MySql/**/*

nats:
  - src/Pulse.Nats/**/*

network:
  - src/Pulse.Network/**/*

npgsql:
  - src/Pulse.NpgSql/**/*

openidconnect:
  - src/Pulse.OpenIdConnectServer/**/*

oracle:
  - src/Pulse.Oracle/**/*

prometheus:
  - src/Pulse.Prometheus.Metrics/**/*
  - src/Pulse.Publisher.Prometheus/**/*

applicationinsights:
  - src/Pulse.Publisher.ApplicationInsights/**/*

cloudwatch:
  - src/Pulse.Publisher.CloudWatch/**/*

datadog:
  - src/Pulse.Publisher.Datadog/**/*

seq:
  -src/Pulse.Publisher.Seq/**/*

rabbitmq:
  - src/Pulse.Rabbitmq/**/*

ravendb:
  - src/Pulse.RavenDB/**/*

redis:
  - src/Pulse.Redis/**/*

sendgrid:
  - src/Pulse.SendGrid/**/*

signalr:
  - src/Pulse.SignalR/**/*

solr:
  - src/Pulse.Solr/**/*

sqlite:
  - src/Pulse.Sqlite/**/*

milvus:
  - src/Pulse.Milvus/**/*

sqlserver:
  - src/Pulse.SqlServer/**/*

system:
  - src/Pulse.System/**/*

UI:
  - src/Pulse.UI/**/*
  - src/Pulse.UI.*/**/*

uris:
  - src/Pulse.Uris/**/*
