name: HealthChecks Prometheus.Metrics CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - src/Pulse.Prometheus.Metrics/**
      - test/Pulse.Prometheus.Metrics.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_prometheus_metrics_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ main ]
    paths:
      - src/Pulse.Prometheus.Metrics/**
      - test/Pulse.Prometheus.Metrics.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_prometheus_metrics_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.Prometheus.Metrics/Pulse.Prometheus.Metrics.csproj
      TEST_PROJECT_PATH: ./test/Pulse.Prometheus.Metrics.Tests/Pulse.Prometheus.Metrics.Tests.csproj
      CODECOV_FLAGS: Prometheus.Metrics
