name: HealthChecks OpenIdConnectServer CD

on:
  push:
    tags:
      - release-openidconnectserver-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.OpenIdConnectServer/Pulse.OpenIdConnectServer.csproj
      PACKAGE_NAME: AspNetCore.Pulse.OpenIdConnectServer
