name: HealthChecks Aws Systems Manager CD

on:
  push:
    tags:
      - release-aws_systemsmanager-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.Aws.SystemsManager/Pulse.Aws.SystemsManager.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Aws.SystemsManager
