name: HealthChecks Gremlin CD

on:
  push:
    tags:
      - release-gremlin-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.Gremlin/Pulse.Gremlin.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Gremlin
