name: HealthChecks Redis CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/Pulse.Redis/**
      - test/Pulse.Redis.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_redis_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/Pulse.Redis/**
      - test/Pulse.Redis.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_redis_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/Pulse.Redis/Pulse.Redis.csproj &&
          dotnet restore ./test/Pulse.Redis.Tests/Pulse.Redis.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/Pulse.Redis/Pulse.Redis.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/Pulse.Redis.Tests/Pulse.Redis.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/Pulse.Redis/Pulse.Redis.csproj &&
          dotnet build --no-restore ./test/Pulse.Redis.Tests/Pulse.Redis.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/Pulse.Redis.Tests/Pulse.Redis.Tests.csproj
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: Redis
          directory: .coverage
