name: HealthChecks DocumentDb CD

on:
  push:
    tags:
      - release-documentdb-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.DocumentDb/Pulse.DocumentDb.csproj
      PACKAGE_NAME: AspNetCore.Pulse.DocumentDb
