name: HealthChecks Publisher.CloudWatch CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/Pulse.Publisher.CloudWatch/**
      - test/Pulse.Publisher.CloudWatch.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_publisher_cloudwatch_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/Pulse.Publisher.CloudWatch/**
      - test/Pulse.Publisher.CloudWatch.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_publisher_cloudwatch_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    env:
      AWS_REGION: us-east-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/Pulse.Publisher.CloudWatch/Pulse.Publisher.CloudWatch.csproj &&
          dotnet restore ./test/Pulse.Publisher.CloudWatch.Tests/Pulse.Publisher.CloudWatch.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/Pulse.Publisher.CloudWatch/Pulse.Publisher.CloudWatch.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/Pulse.Publisher.CloudWatch.Tests/Pulse.Publisher.CloudWatch.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/Pulse.Publisher.CloudWatch/Pulse.Publisher.CloudWatch.csproj &&
          dotnet build --no-restore ./test/Pulse.Publisher.CloudWatch.Tests/Pulse.Publisher.CloudWatch.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/Pulse.Publisher.CloudWatch.Tests/Pulse.Publisher.CloudWatch.Tests.csproj
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: Publisher.CloudWatch
          directory: .coverage
