name: HealthChecks Hangfire CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - src/Pulse.Hangfire/**
      - test/Pulse.Hangfire.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_hangfire_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ main ]
    paths:
      - src/Pulse.Hangfire/**
      - test/Pulse.Hangfire.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_hangfire_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.Hangfire/Pulse.Hangfire.csproj
      TEST_PROJECT_PATH: ./test/Pulse.Hangfire.Tests/Pulse.Hangfire.Tests.csproj
      CODECOV_FLAGS: Hangfire
