name: HealthChecks UI CD

on:
  push:
    tags:
      - release-ui-*
      - release-all-*

jobs:
  build:
    env:
      BUILD_CONFIG: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore UI
        run: dotnet restore ./src/Pulse.UI/Pulse.UI.csproj
      - name: Restore UI.Client
        run: dotnet restore ./src/Pulse.UI.Client/Pulse.UI.Client.csproj
      - name: Restore UI.Core
        run: dotnet restore ./src/Pulse.UI.Core/Pulse.UI.Core.csproj
      - name: Restore UI.Data
        run: dotnet restore ./src/Pulse.UI.Data/Pulse.UI.Data.csproj
      - name: Restore UI.InMemory.Storage
        run: dotnet restore ./src/Pulse.UI.InMemory.Storage/Pulse.UI.InMemory.Storage.csproj
      - name: Restore UI.MySql.Storage
        run: dotnet restore ./src/Pulse.UI.MySql.Storage/Pulse.UI.MySql.Storage.csproj
      - name: Restore UI.PostgreSQL.Storage
        run: dotnet restore ./src/Pulse.UI.PostgreSQL.Storage/Pulse.UI.PostgreSQL.Storage.csproj
      - name: Restore UI.SQLite.Storage
        run: dotnet restore ./src/Pulse.UI.SQLite.Storage/Pulse.UI.SQLite.Storage.csproj
      - name: Restore UI.SqlServer.Storage
        run: dotnet restore ./src/Pulse.UI.SqlServer.Storage/Pulse.UI.SqlServer.Storage.csproj
      - name: Restore UI.K8s.Operator
        run: dotnet restore ./src/Pulse.UI.K8s.Operator/Pulse.UI.K8s.Operator.csproj
      - name: Build UI
        run: dotnet build --no-restore ./src/Pulse.UI/Pulse.UI.csproj -c $BUILD_CONFIG
      - name: Build UI.Client
        run: dotnet build --no-restore ./src/Pulse.UI.Client/Pulse.UI.Client.csproj -c $BUILD_CONFIG
      - name: Build UI.Core
        run: dotnet build --no-restore ./src/Pulse.UI.Core/Pulse.UI.Core.csproj -c $BUILD_CONFIG
      - name: Build UI.Data
        run: dotnet build --no-restore ./src/Pulse.UI.Data/Pulse.UI.Data.csproj -c $BUILD_CONFIG
      - name: Build UI.InMemory.Storage
        run: dotnet build --no-restore ./src/Pulse.UI.InMemory.Storage/Pulse.UI.InMemory.Storage.csproj -c $BUILD_CONFIG
      - name: Build UI.MySql.Storage
        run: dotnet build --no-restore ./src/Pulse.UI.MySql.Storage/Pulse.UI.MySql.Storage.csproj -c $BUILD_CONFIG
      - name: Build UI.PostgreSQL.Storage
        run: dotnet build --no-restore ./src/Pulse.UI.PostgreSQL.Storage/Pulse.UI.PostgreSQL.Storage.csproj -c $BUILD_CONFIG
      - name: Build UI.SQLite.Storage
        run: dotnet build --no-restore ./src/Pulse.UI.SQLite.Storage/Pulse.UI.SQLite.Storage.csproj -c $BUILD_CONFIG
      - name: Build UI.SqlServer.Storage
        run: dotnet build --no-restore ./src/Pulse.UI.SqlServer.Storage/Pulse.UI.SqlServer.Storage.csproj -c $BUILD_CONFIG
      - name: Build UI.K8s.Operator
        run: dotnet build --no-restore ./src/Pulse.UI.K8s.Operator/Pulse.UI.K8s.Operator.csproj -c $BUILD_CONFIG
      - name: Pack UI
        run: dotnet pack --no-build ./src/Pulse.UI/Pulse.UI.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Pack UI.Client
        run: dotnet pack --no-build ./src/Pulse.UI.Client/Pulse.UI.Client.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Pack UI.Core
        run: dotnet pack --no-build ./src/Pulse.UI.Core/Pulse.UI.Core.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Pack UI.Data
        run: dotnet pack --no-build ./src/Pulse.UI.Data/Pulse.UI.Data.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Pack UI.InMemory.Storage
        run: dotnet pack --no-build ./src/Pulse.UI.InMemory.Storage/Pulse.UI.InMemory.Storage.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Pack UI.MySql.Storage
        run: dotnet pack --no-build ./src/Pulse.UI.MySql.Storage/Pulse.UI.MySql.Storage.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Pack UI.PostgreSQL.Storage
        run: dotnet pack --no-build ./src/Pulse.UI.PostgreSQL.Storage/Pulse.UI.PostgreSQL.Storage.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Pack UI.SQLite.Storage
        run: dotnet pack --no-build ./src/Pulse.UI.SQLite.Storage/Pulse.UI.SQLite.Storage.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Pack UI.SqlServer.Storage
        run: dotnet pack --no-build ./src/Pulse.UI.SqlServer.Storage/Pulse.UI.SqlServer.Storage.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Pack UI.K8s.Operator
        run: dotnet pack --no-build ./src/Pulse.UI.K8s.Operator/Pulse.UI.K8s.Operator.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Publish UI Health Check
        run: dotnet nuget push ./artifacts/AspNetCore.Pulse.UI.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish UI.Client Health Check
        run: dotnet nuget push ./artifacts/AspNetCore.Pulse.UI.Client.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish UI.Core Health Check
        run: dotnet nuget push ./artifacts/AspNetCore.Pulse.UI.Core.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish UI.Data Health Check
        run: dotnet nuget push ./artifacts/AspNetCore.Pulse.UI.Data.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish UI.InMemory.Storage Health Check
        run: dotnet nuget push ./artifacts/AspNetCore.Pulse.UI.InMemory.Storage.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish UI.MySql.Storage Health Check
        run: dotnet nuget push ./artifacts/AspNetCore.Pulse.UI.MySql.Storage.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish UI.PostgreSQL.Storage Health Check
        run: dotnet nuget push ./artifacts/AspNetCore.Pulse.UI.PostgreSQL.Storage.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish UI.SQLite.Storage Health Check
        run: dotnet nuget push ./artifacts/AspNetCore.Pulse.UI.SQLite.Storage.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish UI.SqlServer.Storage Health Check
        run: dotnet nuget push ./artifacts/AspNetCore.Pulse.UI.SqlServer.Storage.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish UI.K8s.Operator Health Check
        run: dotnet nuget push ./artifacts/AspNetCore.Pulse.UI.K8s.Operator.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
