name: HealthChecks Aws.SecretsManager CD

on:
  push:
    tags:
      - release-aws_secretsmanager-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.Aws.SecretsManager/Pulse.Aws.SecretsManager.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Aws.SecretsManager
