name: HealthChecks DocumentDb CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/Pulse.DocumentDb/**
      - test/Pulse.DocumentDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_documentdb_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/Pulse.DocumentDb/**
      - test/Pulse.DocumentDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_documentdb_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.DocumentDb/Pulse.DocumentDb.csproj
      TEST_PROJECT_PATH: ./test/Pulse.DocumentDb.Tests/Pulse.DocumentDb.Tests.csproj
      CODECOV_FLAGS: DocumentDb
