name: HealthChecks Azure Blob Storage CD

on:
  push:
    tags:
      - release-azurequeuestorage-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.Azure.Storage.Queues/Pulse.Azure.Storage.Queues.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Azure.Storage.Queues
