name: HealthChecks Publisher.Prometheus CD

on:
  push:
    tags:
      - release-publisher_prometheus-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.Publisher.Prometheus/Pulse.Publisher.Prometheus.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Publisher.Prometheus
