name: HealthChecks Gremlin CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - src/Pulse.Gremlin/**
      - test/Pulse.Gremlin.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_gremlin_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ main ]
    paths:
      - src/Pulse.Gremlin/**
      - test/Pulse.Gremlin.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_gremlin_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      gremlin:
        image: tinkerpop/gremlin-server
        ports:
          - 8182:8182
        env:
          VIRTUAL_HOST: gremlin.docker
          VIRTUAL_PORT: 8182
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/Pulse.Gremlin/Pulse.Gremlin.csproj &&
          dotnet restore ./test/Pulse.Gremlin.Tests/Pulse.Gremlin.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/Pulse.Gremlin/Pulse.Gremlin.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/Pulse.Gremlin.Tests/Pulse.Gremlin.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/Pulse.Gremlin/Pulse.Gremlin.csproj &&
          dotnet build --no-restore ./test/Pulse.Gremlin.Tests/Pulse.Gremlin.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/Pulse.Gremlin.Tests/Pulse.Gremlin.Tests.csproj
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          flags: Gremlin
          directory: .coverage
