name: HealthChecks MongoDb CD

on:
  push:
    tags:
      - release-mongodb-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.MongoDb/Pulse.MongoDb.csproj
      PACKAGE_NAME: AspNetCore.Pulse.MongoDb
