name: HealthChecks Arango DB CI

on:
  workflow_dispatch:
  push:
   branches: [ master ]
   paths:
     - src/Pulse.ArangoDb/**
     - test/Pulse.ArangoDb.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_arangodb_ci.yml
     - Directory.Build.props
     - Directory.Build.targets
   tags-ignore:
     - release-*
     - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/Pulse.ArangoDb/**
      - test/Pulse.ArangoDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_arangodb_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      arangodb:
        image: arangodb/arangodb:latest
        ports:
          - 8529:8529
        env:
          ARANGO_ROOT_PASSWORD: strongArangoDbPassword
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/Pulse.ArangoDb/Pulse.ArangoDb.csproj &&
          dotnet restore ./test/Pulse.ArangoDb.Tests/Pulse.ArangoDb.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/Pulse.ArangoDb/Pulse.ArangoDb.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/Pulse.ArangoDb.Tests/Pulse.ArangoDb.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/Pulse.ArangoDb/Pulse.ArangoDb.csproj &&
          dotnet build --no-restore ./test/Pulse.ArangoDb.Tests/Pulse.ArangoDb.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/Pulse.ArangoDb.Tests/Pulse.ArangoDb.Tests.csproj
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: ArangoDb
          directory: .coverage
