name: HealthChecks Azure EventHubs Preview CD

on:
  push:
    tags:
      - preview-azureeventhubs-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/Pulse.Azure.Messaging.EventHubs/Pulse.Azure.Messaging.EventHubs.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Azure.Messaging.EventHubs
