name: HealthChecks MySql CD

on:
  push:
    tags:
      - release-mysql-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.MySql/Pulse.MySql.csproj
      PACKAGE_NAME: AspNetCore.Pulse.MySql
