name: HealthChecks AzureApplicationInsights CD

on:
  push:
    tags:
      - release-azureapplicationinsights-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.AzureApplicationInsights/Pulse.AzureApplicationInsights.csproj
      PACKAGE_NAME: AspNetCore.Pulse.AzureApplicationInsights
