name: Pulse Application Status CD

on:
  push:
    tags:
      - release-applicationstatus-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.ApplicationStatus/Pulse.ApplicationStatus.csproj
      PACKAGE_NAME: AspNetCore.Pulse.ApplicationStatus
