name: HealthChecks Prometheus.Metrics Preview CD

on:
  push:
    tags:
      - preview-prometheus_metrics-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/Pulse.Prometheus.Metrics/Pulse.Prometheus.Metrics.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Prometheus.Metrics
