name: HealthChecks Aws.SecretsManager Preview CD

on:
  push:
    tags:
      - preview-aws_secretsmanager-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/Pulse.Aws.SecretsManager/Pulse.Aws.SecretsManager.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Aws.SecretsManager
