name: HealthChecks Azure.IoTHub Preview CD

on:
  push:
    tags:
      - preview-azure_iothub-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/Pulse.Azure.IoTHub/Pulse.Azure.IoTHub.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Azure.IoTHub
