name: HealthChecks Dapr CD

on:
  push:
    tags:
      - release-dapr-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.Dapr/Pulse.Dapr.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Dapr
