name: HealthChecks Uris CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - src/Pulse.Uris/**
      - test/Pulse.Uris.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_uris_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ main ]
    paths:
      - src/Pulse.Uris/**
      - test/Pulse.Uris.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_uris_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.Uris/Pulse.Uris.csproj
      TEST_PROJECT_PATH: ./test/Pulse.Uris.Tests/Pulse.Uris.Tests.csproj
      CODECOV_FLAGS: Uris
