name: HealthChecks CosmosDb CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/Pulse.CosmosDb/**
      - test/Pulse.CosmosDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_cosmosdb_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/Pulse.CosmosDb/**
      - test/Pulse.CosmosDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_cosmosdb_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.CosmosDb/Pulse.CosmosDb.csproj
      TEST_PROJECT_PATH: ./test/Pulse.CosmosDb.Tests/Pulse.CosmosDb.Tests.csproj
      CODECOV_FLAGS: CosmosDb
