name: HealthChecks RabbitMQ Preview CD

on:
  push:
    tags:
      - preview-rabbitmq-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/Pulse.Rabbitmq/Pulse.Rabbitmq.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Rabbitmq
