name: HealthChecks DynamoDb CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - src/Pulse.DynamoDb/**
      - test/Pulse.DynamoDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_dynamodb_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ main ]
    paths:
      - src/Pulse.DynamoDb/**
      - test/Pulse.DynamoDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_dynamodb_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.DynamoDb/Pulse.DynamoDb.csproj
      TEST_PROJECT_PATH: ./test/Pulse.DynamoDb.Tests/Pulse.DynamoDb.Tests.csproj
      CODECOV_FLAGS: DynamoDb
