name: HealthChecks AzureApplicationInsights CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/Pulse.AzureApplicationInsights/**
      - test/Pulse.AzureApplicationInsights.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_azureapplicationinsights_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/Pulse.AzureApplicationInsights/**
      - test/Pulse.AzureApplicationInsights.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_azureapplicationinsights_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.AzureApplicationInsights/Pulse.AzureApplicationInsights.csproj
      TEST_PROJECT_PATH: ./test/Pulse.AzureApplicationInsights.Tests/Pulse.AzureApplicationInsights.Tests.csproj
      CODECOV_FLAGS: AzureApplicationInsights
