name: HealthChecks EventStore.gRPC CD

on:
  push:
    tags:
      - release-eventstore_grpc-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.EventStore.gRPC/Pulse.EventStore.gRPC.csproj
      PACKAGE_NAME: AspNetCore.Pulse.EventStore.gRPC
