name: HealthChecks Oracle CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/Pulse.Oracle/**
      - test/Pulse.Oracle.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_oracle_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/Pulse.Oracle/**
      - test/Pulse.Oracle.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_oracle_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      oracle:
        image: gvenzl/oracle-xe:18-slim
        ports:
          - 1521:1521
        env:
          ORACLE_PASSWORD: oracle
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/Pulse.Oracle/Pulse.Oracle.csproj &&
          dotnet restore ./test/Pulse.Oracle.Tests/Pulse.Oracle.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/Pulse.Oracle/Pulse.Oracle.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/Pulse.Oracle.Tests/Pulse.Oracle.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/Pulse.Oracle/Pulse.Oracle.csproj &&
          dotnet build --no-restore ./test/Pulse.Oracle.Tests/Pulse.Oracle.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/Pulse.Oracle.Tests/Pulse.Oracle.Tests.csproj
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          flags: Oracle
          directory: .coverage
