name: HealthChecks Dapr Preview CD

on:
  push:
    tags:
      - preview-dapr-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/Pulse.Dapr/Pulse.Dapr.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Dapr
