name: HealthChecks Arango DB Preview CD

on:
  push:
    tags:
      - preview-arangodb-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/Pulse.ArangoDb/Pulse.ArangoDb.csproj
      PACKAGE_NAME: AspNetCore.Pulse.ArangoDb
