name: HealthChecks EventStore.gRPC CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - src/Pulse.EventStore.gRPC/**
      - test/Pulse.EventStore.gRPC.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_eventstore_grpc_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ main ]
    paths:
      - src/Pulse.EventStore.gRPC/**
      - test/Pulse.EventStore.gRPC.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_eventstore_grpc_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      eventstore:
        image: eventstore/eventstore:lts
        ports:
          - "1113:1113"
          - "2113:2113"
        env:
          EVENTSTORE_INSECURE: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/Pulse.EventStore.gRPC/Pulse.EventStore.gRPC.csproj &&
          dotnet restore ./test/Pulse.EventStore.gRPC.Tests/Pulse.EventStore.gRPC.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/Pulse.EventStore.gRPC/Pulse.EventStore.gRPC.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/Pulse.EventStore.gRPC.Tests/Pulse.EventStore.gRPC.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/Pulse.EventStore.gRPC/Pulse.EventStore.gRPC.csproj &&
          dotnet build --no-restore ./test/Pulse.EventStore.gRPC.Tests/Pulse.EventStore.gRPC.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/Pulse.EventStore.gRPC.Tests/Pulse.EventStore.gRPC.Tests.csproj
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          flags: EventStore.gRPC
          directory: .coverage
