name: HealthChecks Kubernetes CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - src/Pulse.Kubernetes/**
      - test/Pulse.Kubernetes.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_kubernetes_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ main ]
    paths:
      - src/Pulse.Kubernetes/**
      - test/Pulse.Kubernetes.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_kubernetes_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.Kubernetes/Pulse.Kubernetes.csproj
      TEST_PROJECT_PATH: ./test/Pulse.Kubernetes.Tests/Pulse.Kubernetes.Tests.csproj
      CODECOV_FLAGS: Kubernetes
