name: HealthChecks Azure File Storage CD

on:
  push:
    tags:
      - release-azurefilestorage-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.Azure.Storage.Files.Shares/Pulse.Azure.Storage.Files.Shares.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Azure.Storage.Files.Shares
