name: HealthChecks EventStore CI

on:
  push:
    branches: [ master ]
    paths:
      - src/Pulse.EventStore/**
      - test/Pulse.EventStore.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_eventstore_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/Pulse.EventStore/**
      - test/Pulse.EventStore.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_eventstore_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      eventstore:
        image: eventstore/eventstore:lts
        ports:
          - "2113:2113"
          - "1113:1113"
        env:
          EVENTSTORE_INSECURE: true
          EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: true
          EVENTSTORE_ENABLE_EXTERNAL_TCP: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/Pulse.EventStore/Pulse.EventStore.csproj &&
          dotnet restore ./test/Pulse.EventStore.Tests/Pulse.EventStore.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/Pulse.EventStore/Pulse.EventStore.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/Pulse.EventStore.Tests/Pulse.EventStore.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/Pulse.EventStore/Pulse.EventStore.csproj &&
          dotnet build --no-restore ./test/Pulse.EventStore.Tests/Pulse.EventStore.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/Pulse.EventStore.Tests/Pulse.EventStore.Tests.csproj
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          flags: EventStore
          directory: .coverage
