name: HealthChecks Gcp.CloudFirestore CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - src/Pulse.Gcp.CloudFirestore/**
      - test/Pulse.Gcp.CloudFirestore.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_gcp_cloudfirestore_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ main ]
    paths:
      - src/Pulse.Gcp.CloudFirestore/**
      - test/Pulse.Gcp.CloudFirestore.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_gcp_cloudfirestore_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.Gcp.CloudFirestore/Pulse.Gcp.CloudFirestore.csproj
      TEST_PROJECT_PATH: ./test/Pulse.Gcp.CloudFirestore.Tests/Pulse.Gcp.CloudFirestore.Tests.csproj
      CODECOV_FLAGS: Gcp.CloudFirestore
