name: HealthChecks Aws Sns CI

on:
  workflow_dispatch:
  push:
   branches: [ master ]
   paths:
     - src/Pulse.Aws.Sns/**
     - test/Pulse.Aws.Sns.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_aws_sns_ci.yml
     - .github/workflows/reusable_ci_workflow.yml
     - Directory.Build.props
     - Directory.Build.targets
   tags-ignore:
     - release-*
     - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/Pulse.Aws.Sns/**
      - test/Pulse.Aws.Sns.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_aws_sns_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.Aws.Sns/Pulse.Aws.Sns.csproj
      TEST_PROJECT_PATH: ./test/Pulse.Aws.Sns.Tests/Pulse.Aws.Sns.Tests.csproj
      CODECOV_FLAGS: Aws.Sns
