name: HealthChecks Azure Queue Storage CI

on:
  workflow_dispatch:
  push:
   branches: [ main ]
   paths:
     - src/Pulse.Azure.Storage.Queues/**
     - test/Pulse.Azure.Storage.Queues.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_azure_queuestorage_ci.yml
     - .github/workflows/reusable_ci_workflow.yml
     - Directory.Build.props
     - Directory.Build.targets
   tags-ignore:
     - release-*
     - preview-*

  pull_request:
    branches: [ main ]
    paths:
     - src/Pulse.Azure.Storage.Queues/**
     - test/Pulse.Azure.Storage.Queues.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_azure_queuestorage_ci.yml
     - .github/workflows/reusable_ci_workflow.yml
     - Directory.Build.props
     - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.Azure.Storage.Queues/Pulse.Azure.Storage.Queues.csproj
      TEST_PROJECT_PATH: ./test/Pulse.Azure.Storage.Queues.Tests/Pulse.Azure.Storage.Queues.Tests.csproj
      CODECOV_FLAGS: AzureQueueStorage

