name: HealthChecks Aws.S3 CI

on:
  workflow_dispatch:
  push:
   branches: [ main ]
   paths:
     - src/Pulse.Aws.S3/**
     - test/Pulse.Aws.S3.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_aws_s3_ci.yml
     - .github/workflows/reusable_ci_workflow.yml
     - Directory.Build.props
     - Directory.Build.targets
   tags-ignore:
     - release-*
     - preview-*

  pull_request:
    branches: [ main ]
    paths:
      - src/Pulse.Aws.S3/**
      - test/Pulse.Aws.S3.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_aws_s3_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.Aws.S3/Pulse.Aws.S3.csproj
      TEST_PROJECT_PATH: ./test/Pulse.Aws.S3.Tests/Pulse.Aws.S3.Tests.csproj
      CODECOV_FLAGS: Aws.S3
