name: HealthChecks Oracle CD

on:
  push:
    tags:
      - release-oracle-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.Oracle/Pulse.Oracle.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Oracle
