name: HealthChecks Azure.IoTHub CI

on:
  workflow_dispatch:
  push:
   branches: [ master ]
   paths:
     - src/Pulse.Azure.IoTHub/**
     - test/Pulse.Azure.IoTHub.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_azure_iothub_ci.yml
     - .github/workflows/reusable_ci_workflow.yml
     - Directory.Build.props
     - Directory.Build.targets
   tags-ignore:
     - release-*
     - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/Pulse.Azure.IoTHub/**
      - test/Pulse.Azure.IoTHub.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_azure_iothub_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.Azure.IoTHub/Pulse.Azure.IoTHub.csproj
      TEST_PROJECT_PATH: ./test/Pulse.Azure.IoTHub.Tests/Pulse.Azure.IoTHub.Tests.csproj
      CODECOV_FLAGS: Azure.IoTHub
