name: HealthChecks SignalR CD

on:
  push:
    tags:
      - release-signalr-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.SignalR/Pulse.SignalR.csproj
      PACKAGE_NAME: AspNetCore.Pulse.SignalR
