name: HealthChecks Azure Table Storage CD

on:
  push:
    tags:
      - release-azuretablestorage-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/Pulse.Azure.Data.Tables/Pulse.Azure.Data.Tables.csproj
      PACKAGE_NAME: AspNetCore.Pulse.Azure.Data.Tables
