name: HealthChecks Azure KeyVault Secrets CI

on:
  workflow_dispatch:
  push:
   branches: [ main ]
   paths:
     - src/Pulse.Azure.KeyVault.Secrets/**
     - test/Pulse.Azure.KeyVault.Secrets.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_azurekeyvault_secrets_ci.yml
     - .github/workflows/reusable_ci_workflow.yml
     - Directory.Build.props
     - Directory.Build.targets
   tags-ignore:
     - release-*
     - preview-*

  pull_request:
    branches: [ main ]
    paths:
      - src/Pulse.Azure.KeyVault.Secrets/**
      - test/Pulse.Azure.KeyVault.Secrets.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_azurekeyvault_secrets_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/Pulse.Azure.KeyVault.Secrets/Pulse.Azure.KeyVault.Secrets.csproj
      TEST_PROJECT_PATH: ./test/Pulse.Azure.KeyVault.Secrets.Tests/Pulse.Azure.KeyVault.Secrets.Tests.csproj
      CODECOV_FLAGS: AzureKeyVault

